"""target group

Revision ID: 490d6eac9ab5
Revises: b938a569f5bb
Create Date: 2024-09-26 22:57:26.277053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490d6eac9ab5'
down_revision = 'b938a569f5bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_target_groups',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('study_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['study_group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'study_group_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))

    op.drop_table('project_target_groups')
    # ### end Alembic commands ###
