"""user password

Revision ID: b938a569f5bb
Revises: 
Create Date: 2024-09-23 12:39:13.723729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b938a569f5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year_of_entry', sa.Integer(), nullable=False),
    sa.Column('is_foreign', sa.Boolean(), nullable=True),
    sa.Column('type', sa.Enum('B', 'S', 'M', 'A', 'none', name='studygrouptype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('vk_profile', sa.String(length=200), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('student', 'teacher', 'admin', 'mentor', name='userstatus'), nullable=False),
    sa.Column('competency_profile', sa.String(length=500), nullable=True),
    sa.Column('consent_to_share_competency', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['study_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('poster', sa.String(length=200), nullable=True),
    sa.Column('project_type', sa.Enum('scientific', 'technical', 'service', name='projecttype'), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('solution', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('not_confirmed', 'open_recruitment', 'closed_recruitment', 'rejected', name='projectstatus'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('accepted', 'rejected', 'under_review', name='applicationstatus'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_mentors',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('project_mentors')
    op.drop_table('application')
    op.drop_table('project')
    op.drop_table('user')
    op.drop_table('study_group')
    # ### end Alembic commands ###
